# syntax=docker/dockerfile:1
FROM node:20-alpine as builder
WORKDIR /app
COPY package.json package-lock.json* .npmrc* ./
COPY packages ./packages
COPY apps ./apps
COPY tsconfig.base.json ./
RUN npm ci --ignore-scripts
RUN npm run build --workspaces --if-present

FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/package.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/apps ./apps
CMD ["node", "apps/auth-service/dist/main.js"]
